### ISSUE TITLE
[idea] 交大选课插件的 safari 版本合并

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#10]
\cc @dyweb/mos 

idea issuer: @gaocegege

目前选课插件的 safari 版本和 chrome 版本是分离的，经过前期与 @at15 的讨论，可以把两个 repo 合并，因为两者只有配置文件的不同。这样的好处显而易见，不需要保证多个 repo 之间代码版本的统一。

### Tips

合并需要比较了解 chrome 和 safari 中选课插件的运行方式，以及微量的 js 知识。

### reference

* https://github.com/dyweb/electsys-safari
* https://github.com/laohyx/electsys

**Comment by JasonQSY** [comment]
@gaocegege 所以只有配置相关的，i.e. safari插件里的 `Info.plist` 和 chrome 插件的 `manifest.json` 是不一样的，具体的js脚本都全部直接用 chrome 下的版本么。。主要是不太了解插件的兼容问题额

**Comment by gaocegege** [comment]
对的

**Comment by LukeXuan** [comment]
user script能做到么

**Comment by JasonQSY** [comment]
@gaocegege 嗯
@LukeXuan 意思是user script加载js来跨浏览器么

**Comment by gaocegege** [comment]
@LukeXuan user script 门槛太高了，我觉得

**Comment by JasonQSY** [comment]
#dibs
PS：我来吧，就是最近有点忙大概会比较磨叽

**Comment by JasonQSY** [comment]
做了一下移植，没有管自定义option的话work了。现在有个值得讨论的问题是在[load.js](https://github.com/laohyx/electsys/blob/master/content_script/core/load.js)
```
// Support both Chrome & other browsers
if (!browser && chrome) {
    var browser = chrome;
}

jQuery.getJSON(
    browser.extension.getURL("manifest.json"),
    function(data){
        option.set("extension_version", data["version"]);
    }
);
```
写支持但跨不了浏览器. 而`navigator.userAgent.indexOf("Safari") != -1`有判断错误。有必要专门引个库做判断么。
@gaocegege @ComMouse

**Comment by at15** [comment]
@JasonQSY http://stackoverflow.com/questions/5899783/detect-safari-using-jquery 

> Chrome has both 'Chrome' and 'Safari' inside userAgent string.
Safari has only 'Safari'.

**Comment by ComMouse** [comment]
@JasonQSY 原来做的判断是针对 Firefox 和 Edge 的，没有考虑 Safari 的情况，可以视情况调整一下

**Comment by JasonQSY** [comment]
感觉我要鸽了。。最近并没有什么时间写这个。。之前考虑的流程大致可以参考一下

- 移植 `manifest.json` 到 `Info.plist`
- 写一个通用的浏览器判断，可以考虑支持 Firefox, Edge, Safari, Chrome
- 判断完之后，需要逐一确认一下 `browser` 的方法在 Safari 上是否可用， 似乎 Safari 并不是很一样。假如差异比较大，给浏览器单独封装
- (optional) 移植新版的设置页面

**Comment by ComMouse** [comment]
@JasonQSY 目前怎么样了额

**Comment by at15** [comment]
赌 5 毛鸽了

**Comment by JasonQSY** [comment]
咕咕咕
