### ISSUE TITLE
[idea] GitHub OAuth login for Dongyue Q & A

### ISSUE THREAD

**Issue by ComMouse** [dyweb/mos#11]
Since it is convenient to login via GitHub instead of remembering various accounts, we recommend to add this feature to the [Q & A Website](https://qa.tongqu.me).

The source code is [in this repository](https://github.com/dyweb/wecenter). The original project was written in Zend Framework. You may turn to the [official site](http://www.wecenter.com/) for more info.

### Features

* [ ] Login via GitHub
* [ ] Only allow members in GitHub [dyweb](https://github.com/dyweb) organization to login and register

### Skills you will learn

- PHP
- OAuth Implementation
- GitHub API

### Tips

An example of login through GitLab has already been provided [in the source code](https://github.com/dyweb/wecenter/issues/20). You may get started from that implementation.

**Comment by gaocegege** [comment]
@PengZhenghao FYI

If you have any problem in this issue, don't hesitate to ask.

**Comment by at15** [comment]
@PengZhenghao pls change your avatar

**Comment by PengZhenghao** [comment]
Well... Sorry for absence due to the preparation of TOEFL, and now I am free! Thanks for acceptance! And what is going on?...

**Comment by ComMouse** [comment]
@PengZhenghao First you need to set up WeCenter locally... You may refer to the instructions in the WeCenter website.

**Comment by arrowrowe** [comment]
Roadmap for @PengZhenghao, cc @ComMouse:
- [ ] Follow [the official installation instruction of WeCenter](https://github.com/wecenter/wecenter#wecenter-问答系统的安装), ensure that everything works.
- [ ] Update to dyweb's fork: https://github.com/dyweb/wecenter.
- [ ] Read @ComMouse's example for GitLab integeration: https://github.com/dyweb/wecenter/compare/da2626eff8ea5de6896c0e88c26e42284cde15b1...cae65edb29a1a16a91994a6f1ef042f50c4f9b78
- [ ] Learn about GitHub OAuth integeration.
- [ ] Implement.

**Comment by gaocegege** [comment]
Any questions remain? @PengZhenghao 
Feel free to ask.

**Comment by ComMouse** [comment]
Any progess? @PengZhenghao

**Comment by ComMouse** [comment]
Any willing to work on this idea? @PengZhenghao

**Comment by at15** [comment]
Since qa.dongyue.io is gone, I guess we can close it @ComMouse @hebingchang (暴打 boar, 论到你就什么都木了 ... boar: 轮到我之前也基本什么都没了 ....

**Comment by ComMouse** [comment]
I have no objection.

Just close it.
