### ISSUE TITLE
[idea] 为交大毕业论文模板更换开源字体

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#14]
\cc @dyweb/mos 

idea issuer: @gaocegege

Related issue: https://github.com/weijianwen/SJTUThesis/issues/80

## Description

目前，论文用的是 Adobe 的字体，没记错的话是付费的，社区有一个 issue 是关于它的，但是没有人认领。这个工作对简化毕业论文的 LaTeX 环境的搭建很有帮助。

## Related Skills

* LaTeX

**Comment by at15** [comment]
又到了写毕业论文的时候，好忧伤.../w\ 我去看会艾微缓解一下情绪

**Comment by gaocegege** [comment]
对，但是其实是侵犯版权的

**Comment by gaocegege** [comment]
#dibs

**Comment by gaocegege** [comment]
已经为 SJTUThesis 反馈了一个 PR

https://github.com/weijianwen/SJTUThesis/pull/177

**Comment by gaocegege** [comment]
fixed

**Comment by gaocegege** [comment]
https://github.com/weijianwen/SJTUThesis/wiki

更新了一下 wiki：

1. 创建了本地编译使用说明
2. 重命名 usage 为在线编译说明，只记录在线编译的相关文档
3. 修改 Home，加入本地编译说明和在线编译说明的链接

**Comment by gaocegege** [comment]
I Think I have done but the PR haven't been merged, so keep it open.

**Comment by gaocegege** [comment]
https://github.com/weijianwen/SJTUThesis/commit/5f59859dfd1dd5b579bd813aba64d4a969b4140f

PR has been merged, close this issue.

**Comment by gaocegege** [comment]
现在可以在交大论文模板中使用开源的 fandol 字体了，虽然不好看，但是没有版权纠纷。
