### ISSUE TITLE
[idea] Common Golang libraries

### ISSUE THREAD

**Issue by at15** [dyweb/mos#16]
idea issuer: infamous @at15

Related projects: [Ayi](https://github.com/dyweb/Ayi), [xephon-b](https://github.com/xephonhq/xephon-b)

## Description

Since Ayi have already come up with some common libraries, it would be better to make them a standalone project instead of a package instead Ayi, and make it easier to use semver since Ayi may never reach its 1.0 . More detail can be found in recent [blog](http://blog.dongyueweb.com/ayi.html).

Currently, the following are (partially) implemented 

- log: filter by package
- data structure: Set
- requests

following are under progress

- config with template  https://github.com/dyweb/Ayi/issues/65
- process monitor https://github.com/dyweb/Ayi/issues/63

## Required skills

- basic understanding of Golang
- enjoy looking at code of popular libraries
- ~~good at don't starve together and borderland 2~~

## Reference

- https://github.com/go-kit/kit

## Progress

see https://github.com/dyweb/gommon for detail

**Comment by at15** [comment]
I think I will be working on this for now, but I hope I am not the only one, btw, need a name for the repo cc @gaocegege @arrowrowe @ComMouse (we need a team dyweb/naming)

**Comment by ComMouse** [comment]
@at15 `gorun`? `goshen`? `goat15`?

**Comment by arrowrowe** [comment]
@at15 `gommon`?

**Comment by at15** [comment]
Created the new repo as https://github.com/dyweb/gommon and create a new team @dyweb/gopher which only have me and cece for now.

**Comment by ComMouse** [comment]
@at15 How about the progress? =w=

**Comment by at15** [comment]
@ComMouse working on the new version of logging library, but don't have much time to spare recently https://github.com/dyweb/gommon/pull/28 besides, need more people using it to file bugs and feature requests

**Comment by at15** [comment]
close due to I am the only one using gommon ....
