### ISSUE TITLE
[idea] Terms of Service Watcher

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#19]
\cc @dyweb/mos

idea issuer: @gaocegege

## 需求

（1）定期爬取腾讯、网易、知乎、百度等网站的用户协议（http://www.qq.com/contract.shtml ）、隐私条款；
（2）如果较之先前的版本有变化，保存新版的协议内容，并对变化内容进行比较；
（3）可以添加需要跟踪的网站页面；
（4）可能会考虑链接可信时间戳的API。

需求来自交大法学院博士学长

## Related Projects

* https://tosdr.org/index.html https://github.com/tosdr/tosdr.org
* https://github.com/ecprice/newsdiffs

**Comment by gaocegege** [comment]
https://github.com/siglt/tosknight

**Comment by at15** [comment]
这一口狗粮.... 我也有 bot @at15-bot

**Comment by gaocegege** [comment]
@gaocegege-bot 我的有头像

**Comment by at15** [comment]
等我 remaster 我的头像, at15 avatar HD remaster, 1 billion P graph that modern human eyeball can't distinguish

**Comment by gaocegege** [comment]
http://alpha.tosknight.org 阶段性完成

**Comment by xplorld** [comment]
Gaocegege The Go Preacher

**Comment by xplorld** [comment]
假设我想监视大公司 github 项目的 term, 在我没有权限给他们的项目加 ci 的条件下可能实现 hook 吗？还是必须定期查询？

**Comment by at15** [comment]
应该只能轮询，其实效率不会差很多 ... 没人闲的没事整天变 license ref https://github.com/xephonhq/awesome-time-series-database/issues/34

**Comment by xplorld** [comment]
以下几种服务其实是同一种服务：
- deadyet++
- ToS Watcher
- Is Website Down
- mail notifier

**Comment by xplorld** [comment]
maybe an AWS Lambda with cron?

**Comment by gaocegege** [comment]
No money, no AWS.

**Comment by xplorld** [comment]
Heroku with cron is free (if your job is stateless and is small)
