### ISSUE TITLE
[idea] Maintain a fork of SJTUThesis

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#21]
\cc @dyweb/mos \cc @at15 

idea issuer: @gaocegege

SJTUThesis 是由个人维护的,动因是因为我个人觉得 issue 处理比较慢而且很长时间没有 merge 了,我觉得我们可以考虑长期维护一个版本.

**Comment by gaocegege** [comment]
还是跟作者沟通申请成为 collaborator...

**Comment by at15** [comment]
我倾向于 fork，毕竟可能会有一些大的改动 ....

**Comment by gaocegege** [comment]
https://github.com/dyweb/SJTUThesis
