### ISSUE TITLE
[idea] av/ac/sm/pixiv/?? detector

### ISSUE THREAD

**Issue by xplorld** [dyweb/mos#26]
# motivation
当你看到一个 av 号，不能点开，还需要搜索，就很不爽

# spec

A chrome extension

in any HTML page: if exist `av\d+` in content, replace to `<a href="http://bilibili.com/video/av123...1"> av123...1</a>`, others similar

# features

- extensible: no hardcoded rules, all rules customizable
- performance: not too slow...

# design

set up several rules.

Rule = match(regex) + replace(HTML)

# alternative designs

a link may be disturbing. Maybe a 下拉菜单 is acceptable? 
![default](https://user-images.githubusercontent.com/7023694/38160607-74fbdb34-3475-11e8-8215-8a53a4c79153.png)

# evaluation

- hardness: easy
- beginners can do: true
- time cost: 5 hours for experienced
- may be popular: true

**Comment by xplorld** [comment]
> @xiaodou: 神秘代码转换器

**Comment by xplorld** [comment]
如果做成右键下拉菜单就不需要在打开网页时候扫描了， 0 overhead, 但是不知道体验如何，还得选中

**Comment by voldikss** [comment]
#dibs  https://github.com/dyweb/acg-detector

**Comment by xplorld** [comment]
我应该是全东岳最没有行动力的人了。。。

**Comment by gaocegege** [comment]
Thank @clouduan for the implementation!

**Comment by gaocegege** [comment]
@xplorld 

ruiyang 这样的 CMU 大佬只需要发需求就好了，实现的工作交给我们这样的来做 :微笑:

**Comment by xplorld** [comment]
sad_rabbit.jpg
