### ISSUE TITLE
[donation] Transfer go.ice to dyweb from at15

### ISSUE THREAD

**Issue by at15** [dyweb/mos#31]
I am still maintaining go.ice. (没有弃坑, 骄傲

By transfering it to dyweb, I hope more folks can participate in it. (The true reason is I can @gaocegege easier ....)

TODO

- [x] transfer the repo https://github.com/dyweb/go.ice
- [x] fix the import path in repo https://github.com/dyweb/go.ice/commit/9f22a102ab976bb59e5ec872fcdbd50a9cbcbacd
- [x] make sure CI is working
- [ ] fix import in projects depends on go.ice

btw: cc @gaocegege  I think we should make use of the new multiple github issue template feature

**Comment by gaocegege** [comment]
SGTM

**Comment by at15** [comment]
there aren't many projects relies on go.ice, dy-bot uses go.ice, but thanks to package management it still works until someone run `dep ensure -update`, I will make a PR to dy-bot later

**Comment by gaocegege** [comment]
Yeah, thanks for your contribution
