### ISSUE TITLE
[idea] Make a permanent URL to the latest weekly issue page

### ISSUE THREAD

**Issue by xplorld** [dyweb/mos#33]
a bot.

cron'd weekly. (pun intended)

actions:

1. close old issue
2. call the rust code to generate weekly
3. open a new issue
4. redirect a permanent URL to the latest weekly issue page to ease submission. e.g. 
`https://dongyueweb.com/weekly/latest` or `https://wangruiyang.com/weekly/latest`

**Comment by at15** [comment]
I think @gaocegege already have one and see https://github.com/dyweb/dy-bot , though I think latter is no longer (if ever) under active development

**Comment by xplorld** [comment]
thought for a while and realized my actual need is the bookmarklet. However, it is not perfect because I also post new things in mobile where I did not set up proper bookmark sync mechanism. Considering host the bookmarklet to my site or to `dongyueweb.com`...

**Comment by xplorld** [comment]
No, if I use that script to host a latest entry, my github token would be exposed...

**Comment by gaocegege** [comment]
We already have it now https://github.com/dyweb/weekly/#source-code
