### ISSUE TITLE
[idea] Kharosthi numbers to/from int converter

### ISSUE THREAD

**Issue by xplorld** [dyweb/mos#36]
# Background

[Kharosthi 犍陀羅文](https://www.wikiwand.com/en/Kharosthi) is a kind of writing system derived from egypt, used in ancient Gandhara (now Pakistan and eastern Afghanistan.

They have a special kind of number system: right-to-left, special characters, and special number composition rules.

 For example, the number 1996 would be written as 1000 4 4 1 100 20 20 20 20 10 4 2 (
![image](https://user-images.githubusercontent.com/7023694/50368851-c0f7f700-0541-11e9-83e5-1ece88cebc00.png)
, text: 𐩇𐩃𐩃𐩀𐩆𐩅𐩅𐩅𐩅𐩄𐩃𐩁).

# Unicode support

Unicode has support for Kharosthi alphabets, and in Python 3, `'𐩇𐩃𐩃𐩀𐩆𐩅𐩅𐩅𐩅𐩄𐩃𐩁'.isnumeric()` returns `True`, as defined in Unicode standard.

# Significance

There is no available Kharosthi-to-arabic number converter exist. It is assumed that Kharosthi experts use their brain and calculator to do so. It would be a help for them if there is an online converter.

Besides, it is a good practise for those who would like to write a little JavaScript and have a brief poke into the Unicode standard.

**Comment by xplorld** [comment]
# Design

Frontend only. A simple static web page including:

- WebFont of Kharosthi numerals
- JS script to do transformation
- Well designed UI

**Comment by xplorld** [comment]
https://wangruiyang.com/KharosthiNumerals/

**Comment by gaocegege** [comment]
就很强
