### ISSUE TITLE
[idea] Github Contribution Color Extension

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#4]
\cc @dyweb/mos 

idea issuer: @gaocegege

> <img width="938" alt="2016-10-31 10 55 35" src="https://cloud.githubusercontent.com/assets/5100735/19843097/1699c080-9f5a-11e6-9773-daa55ac62ab6.png">

> Github 会在一些节假日变换 contribution bar 的颜色，希望实现自定义的功能，更深一步可以支持自设节日，比如在你生日变成迷人的粉红色，在你女朋友生日变成警示的红色，在 trump 当选纪念日变成令人绝望的黑色，等等

目测要求：

1. 会写 js 即可
2. 可以阅读英文文档

**Comment by gaocegege** [comment]
这个idea，大家资此不资此啊

**Comment by arrowrowe** [comment]
0.0 是要做什么呢? [jasonlong/isometric-contributions](https://github.com/jasonlong/isometric-contributions) 这样的 Chrome extension? 还是 [IonicaBizau/ghcal](https://github.com/IonicaBizau/ghcal) 这样活在命令行里的?

**Comment by gaocegege** [comment]
前者，可以改变 contribution bar 的颜色

**Comment by xplorld** [comment]
trump:???

**Comment by xplorld** [comment]
以及这个并不难吧，换 css 就行。主要是怎么做策略：什么节日换什么颜色，这个是要用户定义的还是插件vendor（dyweb）定义的？

**Comment by gaocegege** [comment]
@xplorld 非常简单，策略我觉得可以支持自定义最好

**Comment by arrowrowe** [comment]
@xplorld `exp/beginner` & `size/small` :smile:

**Comment by gigaflw** [comment]
Emm... It seems this project haven't started for a year.
I find this interesting though, can I offer to do it?

**Comment by LukeXuan** [comment]
You're  welcome

**Comment by gaocegege** [comment]
Of course

**Comment by gaocegege** [comment]
Feel free to let us know the progress and I'd glad to be the very early user :-)

**Comment by ComMouse** [comment]
FYI https://github.com/dyweb/colorful-contribution

**Comment by ComMouse** [comment]
@gigaflw What about the progress =w=

**Comment by gigaflw** [comment]
Oh, I am having my final exams, so... 🤣 
I believe it will be done soon

**Comment by gigaflw** [comment]
It finally gets into shape, takes much more time than I expected...
https://github.com/dyweb/colorful-contribution/releases
Would anyone like to try ? @gaocegege @ComMouse 

BTW, since it takes lots of procedures to activate chrome develop account, I will probably leave that aside for now...

**Comment by clouduan** [comment]
Awesome！

**Comment by gaocegege** [comment]
I will have a try! Definitely cool!!!!!!!!!

**Comment by clouduan** [comment]
在添加新的自定义主题时，点击 + 号无法实时生成，只有重新点击 popup 页面时才会显示 Newbie。

**Comment by gigaflw** [comment]
whoops, fixed

**Comment by gaocegege** [comment]
Thank @gigaflw for the implementation！

**Comment by at15** [comment]
@ComMouse 可以用老贺的帐号发布一下？ 或者东岳再搞一个? @gaocegege

**Comment by gaocegege** [comment]
@at15 建立一个会更合适些，我们还有一个等着发布呢 /cc @clouduan

**Comment by at15** [comment]
那这个任务就交给身为组长的你? @gaocegege

**Comment by voldikss** [comment]
@gaocegege 我那个可能还需要很多优化（毕竟赶制成的，太简陋

**Comment by gaocegege** [comment]
@at15 我觉得还是交给东岳话事人 @at15 好

@clouduan 没关系，可以先发布，没必要完全做好了再发布，快速迭代嘛

**Comment by at15** [comment]
@gaocegege 开个 issue assign 给我好了 .... 我肯定会忘的

**Comment by gaocegege** [comment]
要验证帐号和发布项目，您需要支付 US$5.00的一次性开发者注册费。

婶婶有钱么，要不还是用老贺的账号吧。。

**Comment by at15** [comment]
@gaocegege 有 .w. 一顿食堂的饭就够付 2 次注册费了 ...
