### ISSUE TITLE
append intro to members.md

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#5]
Append your intro to [members.md](https://github.com/dyweb/mos/blob/master/members.md), plz.

The job could be done in a variety of ways:

1. update the readme.md and push it to this remote.
2. fork a new repo and update it, then file a PR.

Whatever you want:)

Due: it doesn't have a due date.

**Comment by brucechin** [comment]
我是秦连柯（brucechin） 
我是一个：
       刚投入软工怀抱的大二狗
       缺少大一正规训练，目前正在恶补基础的学渣
       已戒游戏，仍喜欢看书打网球

**Comment by JasonQSY** [comment]
@gaocegege I've appended.

**Comment by gaocegege** [comment]
需要更新到 https://github.com/dyweb/mos/blob/master/README.md 里

另外 issue 一般是发起的人来 close，被 assign 的人做完后回复 PTAL(Plz take a look) 就可以了

**Comment by ComMouse** [comment]
强势围观

**Comment by arrowrowe** [comment]
@gaocegege 要不要把成员列表从 readme 里剥出来? 似乎越来越长了 = =

**Comment by gaocegege** [comment]
@arrowrowe 是的。。

**Comment by at15** [comment]
@brucechin tennis!

**Comment by gaocegege** [comment]
@JosephKim6 FYI

**Comment by arrowrowe** [comment]
@JosephKim6 please accept the invitation to team Mos here: https://github.com/dyweb

**Comment by gaocegege** [comment]
@bertlps @CR-Gjx
FYI

**Comment by bertlps** [comment]
PTAL

**Comment by gaocegege** [comment]
LGTM, Thks.

**Comment by gaocegege** [comment]
@xplorld FYI

**Comment by gaocegege** [comment]
@gigaflw FYI

**Comment by gigaflw** [comment]
PTAL

**Comment by gaocegege** [comment]
LGTM
