### ISSUE TITLE
[idea] Dongyue HR system

### ISSUE THREAD

**Issue by ComMouse** [dyweb/mos#8]
Since we're in lack of such a HR system and the recruitment will be finished soon.... A convenient HR info collecting system is necessary at the moment.

The technique stack MUST be suitable for long-term maintenence, so PHP is more preferred in this project. We suggest you get started with Laravel cause it does well in agile development.

The features of the system are listed below. Items marked with `Optional` may not be included in the initial version.

* [x] Registration by e-mail, hashed password (e.g. with bcrypt algorithm) should be collected to register other services in our team, like GitLab Tq, QA, etc.
* [x] Personal information filling in (see dy/guide repo on GitLab)
* [ ] (Optional) Simple Access Control List (separated by teams, e.g. Web, Android, ...)
* [ ] (Optional) Self-service registration of our services like GitLab Tq, QA, etc.
* [ ] (Optional) Synchronize with the team address list at GitLab dy/guide repo

**Additional Tips on this project**

For a beginner in Web development, you may only need to take a week or so to get the preliminary features finished. Features are more important than good-looking user interface and well-organized code (since it's simple enough).

**Comment by GigaFlower** [comment]
我有兴趣

我来留言

**Comment by ComMouse** [comment]
@GigaFlower See https://github.com/dyweb/mos/blob/master/idea-intro.md for idea assigning guides.

**Comment by gaocegege** [comment]
Hi, has there been any progress on that front? 
What can we do for you?
😸

**Comment by ComMouse** [comment]
Your hug~

**Comment by ComMouse** [comment]
=_=

**Comment by GigaFlower** [comment]
Sorry for no progress and failed to response timely.
I'll begin my work in no time.

**Comment by ComMouse** [comment]
It seems done a long time ago....... Close this issue? @gigaflw

**Comment by at15** [comment]
@ComMouse do we have it running?

**Comment by ComMouse** [comment]
Never have it run, may try it later
