### ISSUE TITLE
[idea] 交大选课插件的 firefox 版本维护

### ISSUE THREAD

**Issue by gaocegege** [dyweb/mos#9]
\cc @dyweb/mos 

idea issuer: @hczhcz

ref https://github.com/laohyx/electsys/issues/20

>长话短说，[Firefox 插件](https://github.com/hczhcz/electsys)的代码过时了，如果还有人在用它的话，欢迎来维护。主要的维护工作是保持 content script 和这边同步，做必要的测试，以及上传给 Mozilla 做签名。
>
>一些技术细节：目前插件只使用了 content script。`./content/init.js`会检测当前页面是不是 electsys，并装载脚本。因此，引入新的脚本后需要把它加在`./content/init.js`的列表里。另外，每次更新后，`./install.rdf`里需要修改版本号和 Firefox 的版本兼容范围。
>
>愿意来做 collaborator 的欢迎报名 :-)

**Comment by ComMouse** [comment]
Close? @gaocegege

**Comment by arrowrowe** [comment]
Got volunteers?

**Comment by ComMouse** [comment]
Seems got

**Comment by arrowrowe** [comment]
Then update and close?

**Comment by hczhcz** [comment]
Seems good to close.

BTW, feel free to let us know if you are interested in being a collaborator :-)
